// Generated by web/emu/forge/gen_config.py from the firmware's sdkconfig: the framework's and the app's values.
#pragma once
#define CONFIG_APP_TZ "EST5EDT,M3.2.0,M11.1.0"
#define CONFIG_FORGE_SETUP_SSID "RTC-Setup"
#define CONFIG_FORGE_TLS_NAME "RTC Quebec display"
#define CONFIG_FORGE_REPO "TheMonkeyz/esp32-s3-rtcquebec"
#define CONFIG_FORGE_PRODUCT ""
#define CONFIG_FORGE_UA_COMMENT ""
#define CONFIG_FORGE_PORTAL_NAME ""
#define CONFIG_FORGE_OTA_SITE "https://themonkeyz.github.io/esp32-s3-rtcquebec/"
